# Generated by Django 3.2.18 on 2023-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('critic', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_oneline',
            field=models.ManyToManyField(related_name='like_oneline_user', to='critic.Oneline'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reply',
            field=models.ManyToManyField(related_name='like_reply_user', to='critic.Reply'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
