# Generated by Django 3.2.18 on 2023-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_pk',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
